import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  function Todo() {
    const getKey = () => Math.random().toString(32).substring(2);
    const [items, setItems] = React.useState([
      { key: getKey(), text: 'Learn JavaScript', done: false },
      { key: getKey(), text: 'Learn React', done: false },
      { key: getKey(), text: 'Get some good sleep', done: false },
    ]);

    return (
      <div className='panel'>
        <div className='panel-heading'>
          React Todo
        </div>

        {items.map(item => (
          <label className='panel-block'>
            <input type='checkbox' />
            {item.text}
          </label>
        ))}
        <div className='panel-block'>
          {items.length} items
        </div>
      </div>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.8.2/css/bulma.min.css" />
      </Head>
      <main className={styles.main}>
        <Todo />
      </main>
    </>
  )
}
